config/routes.rb
Rails.application.routes.draw do

  root 'restaurants#index'

  get '/logout' => 'sessions#destroy'
  get '/account' => 'users#show'
  get '/wall/:id' => 'lists#show'
  get '/initial' => 'sessions#create'
  post '/yelp' => 'restaurants#search'
  post '/follow' => 'users#follow'
  get '/recommendations' => 'lists#recommend'

  get '/favorites/new' => 'favorites#new'
  post 'favorites' => 'favorites#create'
  patch 'favorites/:id' => 'favorites#edit'

  resources :restaurants
  resources :users
  resources :reviews
  resources :sessions
  resources :lists

  # get '/restaurants' => 'restaurants#index'
  # get '/restaurants/new' => 'restaurants#new'
  # post '/restaurants' => 'restaurants#create'
  # get '/restaurants/:id' => 'restaurants#show'
  # get '/restaurants/:id/edit' => 'restaurants#edit'
  # patch '/restaurants/:id' => 'restaurants#update'
  # delete '/restaurants/:id' => 'restaurants#destroy'
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	belongs_to :neighborhood
	belongs_to :category
	has_many :lists
	has_many :users, :through => :lists

  has_many :favorites
  has_many :userfavorites, class_name: "Favorite", foreign_key: "restaurant_id"

	validates_presence_of :name

	# in order to avoid duplicate listings of manually added restaurants
	# name is checked for uniqueness within the scope of a neighborhood
	# allowing for restaurants with multiple locations.
	validates_uniqueness_of :name, scope: :neighborhood, :case_sensitive => false

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		if params["keyword"].present?
			k = params["keyword"].strip.downcase
			@restaurants = Restaurant.where("lower(name) LIKE ?", "%#{k}%").limit(10000).page(params[:page]).per(20)
		else
			@restaurants = Restaurant.limit(10000).page(params[:page]).per(20)
		end
	end

	def show
		@restaurant = Restaurant.find_by(:id => params["id"])
	end 

	def update
		restaurant = Restaurant.find_by(:id => params["id"])
		restaurant.name = params["name"]
		restaurant.category_id = params["category_id"]
		restaurant.neighborhood_id = params["neighborhood_id"]
		restaurant.address = params["address"]
		restaurant.rating = params["rating"]
		restaurant.image_url = params["image_url"]
		restaurant.save

		redirect_to root_url
	end

	def edit
		@restaurant = Restaurant.find_by(:id => params["id"])
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		restaurant = Restaurant.new
		restaurant.name = params["name"]
		restaurant.category_id = params["category_id"]
		restaurant.neighborhood_id = params["neighborhood_id"]
		restaurant.address = params["address"]
		restaurant.rating = params["rating"]

		# editing string to link to a higher res photo from yelp
		# original API response is 100x100
		img = params["image_url"].chomp('ms.jpg') << "l.jpg"
		restaurant.image_url = img

		if restaurant.save
			flash[:notice] = "#{restaurant.name} added to FoodEase"

			# this parameter diferentiates the button to both add to foodease
			# and to add to your wall
			if params[:list_user_id]
				list = List.new
				list.restaurant_id = restaurant.id
				list.user_id = session[:user_id]

				if list.save
					flash[:notice] = "#{restaurant.name} added to your wall."
				else
					flash[:error] ="#{restaurant.id} was already on your wall."
				end
			end
		else
			flash[:error] = "#{restaurant.name} is already on Foodease"
		end



		redirect_to root_url

	end

	def destroy
		@restaurant = Restaurant.find_by(:id => params["id"])
		@restaurant.delete
		redirect_to "/restaurants"
	end

	def search
    	parameters = { term: params[:term], limit: 10, category_filter: 'restaurants' }
    	@response = Yelp.client.search('Chicago', parameters)
  	end

end

app/views/restaurants/edit.html.erb
<h1> Edit an existing restaurant </h1>

<% if @restaurant.errors.any? %>
	<p> @restaurant.errors.full_messages%> </p>
<% end %>

<%= form_tag "/restaurants/#{@restaurant.id}", :method => "patch" do %>
	<div>
		<label> Restaurant Name:</label>
		<input type="text" size = "35" name="name" value="<%=@restaurant.name%>">
	</div>

	<div>
		<label>Category: </label>
		<select name="category_id">
			<% Category.order('name').all.each do |category| %>
				<% if category.id == @restaurant.category_id %>
					<option selected="selected" value="<%=category.id%>">
					<%= category.name %>
				<% else %>
					<option value="<%= category.id %>"><%= category.name %></option>
				<% end %>
			<% end %>
		</select>
	</div>

	<div>
		<label>Neighborhood: </label>
		<select name="neighborhood_id">
			<% Neighborhood.order('name').all.each do |neighborhood| %>
				<% if neighborhood.id == @restaurant.neighborhood_id%>
					<option selected="selected" value="<%= neighborhood.id %>">
					<%= neighborhood.name %></option>
				<% else %>
					<option value="<%= neighborhood.id %>">
					<%= neighborhood.name %></option>
				<% end %>
			<% end %>
		</select>
	</div>
	<div>
		<label> Address:</label>
		<input type="text" size="50" name="address" value="<%=@restaurant.address%>">
	</div>

	<div>
		<label> Rating (1-5):</label>
		<input type="number" name="rating" value="<%=@restaurant.rating%>" min="1" max="5" step ="0.5">
	</div>

	<div>
		<label> Image URL:</label>
		<input type="text" size="50" name="image_url" value="<%=@restaurant.image_url%>">
	</div>

	<input type="submit" value="Update Restaurant">

<% end %>

app/views/restaurants/index.html.erb
<%if !session[:user_id] %> 
  <div class="jumbotron" style="overflow: hidden">
    <h1>Welcome to FoodEase</h1>
    <p>Keep track of your favorite restaurants in Chicago and find new restaurants that people with similar tastes already know about.  </p>

    <p><a class="btn btn-primary btn-lg" href="/users/new" role="button">Sign Me Up!</a></p>
    <%= image_tag "screenshot1.png", :class=>"landing-thumbnail"%>
    <%= image_tag "screenshot2.png", :class=>"landing-thumbnail"%>
  </div>
<% else %>
	<h1>
		<% if !params["keyword"].present? %>
			<span id= "restaurant-header">Browse All Restaurants</span>
		<% end %>
		<% if session[:user_id] %>
	  	<small>
	    	<a class="btn btn-success pull-right" style="background-color:#009900" 
	    		href="/restaurants/new">Add a new restaurant</a>
	  	</small>
	  <% end %>
	</h1>

	<% if !params["keyword"].present? %>
		<p>Browse the <%= Restaurant.all.count%> restaurants currently available on FoodEase</p>
	<% else %>
		<p>Displaying results for search: "<%= params["keyword"] %>"</p>
	<% end %>

	<%= paginate @restaurants %>

	<table class='table table-striped'>
		<thead>
			<tr>
				<th width="30%">Name</th>
				<th>Category</th>
				<th>Neighborhood</th>
				<th>Rating</th>
			</tr>
		</thead>
		<tbody>
			<% @restaurants.order('name').each do |restaurant| %>
				<tr>

					<td>
						<%= link_to restaurant.name, "/restaurants/#{restaurant.id}" %>
					</td>

					<td>
						<%= restaurant.category.name %>
					</td>

					<td>
						<%= restaurant.neighborhood.name %>
					</td>

					<td>
						<%= restaurant.rating%>
					</td>

					<% if session[:user_id] %>
						<%if User.find(session[:user_id]).admin%>
							<td>
								<%= link_to "Delete", "/restaurants/#{restaurant.id}", :method => "delete" %>
							</td>

							<td>
								<%= link_to "Edit", "/restaurants/#{restaurant.id}/edit" %>
							</td>
						<% end %>

						<td>
							<%= button_to "Add to Your Wall", lists_path, params: {:restaurant_id => restaurant.id}, :class => "btn btn-primary btn-xs" %>
						</td>
					<% end %>
				</tr>
			<% end %>
		</tbody>
	</table>

	<%= paginate @restaurants %>

<% end %>

app/views/restaurants/new.html.erb
<h1> Search for your restaurant using Yelp! </h1>

<% if @restaurant.errors.any? %>
	<p> <%=@restaurant.errors.full_messages%> </p>
<% end %>

<%= form_tag "/yelp" do %>
	<p><%= label_tag :term, "Enter a search term to find a restaurant: " %></p>
    <p><%= text_field_tag :term %></p>
    <%= submit_tag "Search for Restaurant" %>
<% end %>

<h2> Manually Add your restaurant </h2>

<%= form_tag "/restaurants" do %>
	<div>
		<label>Restaurant Name: </label>
		<input type="text" size="35" name="name" value="<%=@restaurant.name%>">
	</div>

	<div>
		<label>Category: </label>
		<select name="category_id">
			<% Category.order('name').all.each do |c| %>
				<% if c.id == @restaurant.category_id %>
					<option selected="selected" value="<%=c.id%>">
					<%= c.name %>
				<% else %>
					<option value="<%= c.id %>"><%= c.name %></option>
				<% end %>
			<% end %>
		</select>
	</div>

	<div>
		<label>Neighborhood: </label>
		<select name="neighborhood_id">
			<% Neighborhood.order('name').all.each do |n| %>
				<% if n.id == @restaurant.neighborhood_id %>
					<option selected="selected" value="<%=n.id%>">
					<%= n.name %>
				<% else %>
					<option value="<%= n.id %>"><%= n.name %></option>
				<% end %>
			<% end %>
		</select>
	</div>

	<div>
		<label>Address: </label>
		<input type="text" size="50" name="address" value="<%=@restaurant.address%>">
	</div>

	<div>
		<label>Rating (1-5): </label>
		<input type="number" name="rating" value="<%=@restaurant.rating%>" min="1" max="5" step="0.5">
	</div>

	<div>
		<label>Image URL: </label>
		<input type="text" size="50" name="image_url" value="<%=@restaurant.image_url%>">
	</div>

	<input type="submit" value="Add Restaurant">

<% end %>

app/views/restaurants/search.html.erb
<h3 style="text-align: center"> Search Results </h3>

<!-- If the search result is not in chicago, the neighborhood field is empty -->
<% if @response.total == 0 %>
	<h4 style = "text-align: center; padding-top: 100px">Sorry! No Results Found</h4>
<% end %> 

<div class="container">
	<% @response.businesses.each do |r|%> 
		
		<!-- assigns neighborhood or city if no neighborhood present -->
		<% neighborhood = r.location.neighborhoods[0] rescue r.location.city %>


		<!-- provide default image if none provided in Yelp API response -->
		<% image = r.image_url rescue image = "http://images.clipartpanda.com/spoon-clipart-black-and-white-knife-and-fork-clipart-white.svg" %>

		<div class="row">
			<div class="search-element">

					<span><%= image_tag image, :class => "search-thumbnail" %></span>

				<div class="col-md-6 col-md-offset-2">
					<ul class="plain">
						<li class= "list-link"><%= r.name%></li>
						<li><%= r.categories[0][0]%></li>
						<li><%= neighborhood %></li>
					</ul>
				</div>

				<!-- Convert the category into an id number, or create new category if necessary-->
				<% c = Category.find_by(name: r.categories[0][0])%>
				<% if c == nil %>
					<%category = Category.new%>
					<%category.name = r.categories[0][0]%>
					<%category.save%>
					<%cat_id = category.id%>
				<% else %>
					<%cat_id = c.id%>
				<% end %>

				<!-- Convert the category into an id number, or create new category if necessary-->
				<% n = Neighborhood.find_by(name: neighborhood)%>
				<% if n == nil %>
					<%n = Neighborhood.new%>
					<%n.name = neighborhood%>
					<%n.save%>
				<% end %>
					
				<%n_id = n.id%>

				<div class="col-md-2">
					<div style="margin: auto; margin-top: 15px; ">
						<%= button_to "Add to FoodEase", restaurants_path, 
							params: {:name => r.name, :category_id => cat_id, :neighborhood_id => n_id,
						         :rating => r.rating, :address => r.location.address, 
						         :image_url=> image},
							:class => "btn btn-primary btn-xs" %>
					</div>

					<div style="margin: auto; margin-top: 15px">
						<%= button_to "Add to Your Wall and FoodEase", restaurants_path, 
							params: {:name => r.name, :category_id => cat_id, :neighborhood_id => n_id,
						         :rating => r.rating, :address => r.location.address, 
						         :image_url=> image, :list_user_id => session[:user_id]},
							:class => "btn btn-primary btn-xs" %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="restaurant">
  <h2><%= @restaurant.name %>
    <span class="rating"><%= @restaurant.rating %></span>
  </h2>
  <h5><%= @restaurant.category.name %></h5>
  <h5><%= @restaurant.neighborhood.name %></h5>
  <h5><%= @restaurant.address %></h5>

  <%= image_tag @restaurant.image_url, :height => '300', :style=>"margin-bottom: 5px" %>

</div>


<% favs = @restaurant.userfavorites %> 

<div class="container">
	<div class="row">
	  <div class="col-md-5">
			<div class="followed-users-box" style="text-align: center">
				<h4 style="text-align: center">Users with this restaurant in their Top 3</h4>
				<% if favs.count == 0 %>
					No one yet.
				<% end %>
				<% favs.each do |fav| %>
				  <% if fav.number == 1 %>
						<%= link_to fav.user.username, "/wall/#{fav.user.id}", 
						:class =>"btn btn-info", :style=>"margin: 2px; margin-bottom:4px; 
						display: inline-block; background-color: #F0C714; border: 1px solid black"%>
					<% elsif fav.number == 2 %>
						<%= link_to fav.user.username, "/wall/#{fav.user.id}", 
						:class =>"btn btn-info", :style=>"margin: 2px; margin-bottom:4px; 
						display: inline-block; background-color: #C0C0C0; border: 1px solid black"%>
					<% else %>
						<%= link_to fav.user.username, "/wall/#{fav.user.id}", 
						:class =>"btn btn-info", :style=>"margin: 2px; margin-bottom:4px; 
						display: inline-block; background-color: #CD7F32; border: 1px solid black"%>
					<% end %>
				<% end %>
			</div>
		</div>

		<div class="col-md-2" style="text-align: center; margin-top: 10px">
			<%if session[:user_id] %>
				<%= button_to "Add to Your Wall", lists_path, params: {:restaurant_id => @restaurant.id}, 
				:class => "btn btn-primary" %>
			<% end %>
		</div>

	  <div class="col-md-5">
			<div class="followed-users-box" style="text-align: center">
				<h4 style="text-align: center">Users that posted this restaurant to their wall</h4>
				<% @restaurant.users.each do |user| %>
					<%= link_to user.username, "/wall/#{user.id}", 
					:class =>"btn btn-info", :style=>"margin: 2px; margin-bottom:4px; display: inline-block"%>
				<% end %>
			</div>
		</div>
	</div>

	<% connected_restaurants = List.where(:user_id => @restaurant.users) %>

	<% connected_restaurants = connected_restaurants.where.not(:restaurant_id => @restaurant.id) %>

	<%top = connected_restaurants.group('restaurant_id').order('count_restaurant_id DESC').limit(9).count('restaurant_id').to_a%>

	<h3 style="text-align: center; text-decoration: underline"> Users that like <%=@restaurant.name%> also like these restaurants </h3>

	<% top.in_groups_of(3, false) do |top_rows| %>
			<div class="row">
				<% for t in top_rows %>
					<% top_res = Restaurant.find(t.first) %>
					<div class="col-md-4" style="padding: 5px">
						<div class="square-list-element" style="text-align: center">
							<div class="row">
								<div class="col-md-3 col-md-12">
									<span><%= image_tag top_res.image_url, :class => "square-list-thumbnail" %></span>
								</div>

								<div class="col-md-7 col-md-12">
									<% if top_res.name.length > 15 %>
										<ul class="wall2" style="text-align: center; width:100%">
											<li><%= link_to top_res.name, "/restaurants/#{top_res.id}", 
												:class => "list-link" %>
											</li>
											<li><%= top_res.category.name %></li>
											<li><%= top_res.neighborhood.name %></li>
										</ul>
									<% else %>
										<ul class="wall" style="text-align: center">
											<li><%= link_to top_res.name, "/restaurants/#{top_res.id}", 
												:class => "list-link" %>
											</li>
											<li><%= top_res.category.name %></li>
											<li><%= top_res.neighborhood.name %></li>
										</ul>
									<% end %>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
	<% end %>
</div>